#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

echo "
install.sh
download.sh
$(printf '%s\n' script/*)
$(
  git ls-files --exclude-standard -co '.*' |
    grep -v .gitignore |
    grep -v .gitconfig
)" | xargs script/shfmt \
  --write \
  --indent 2
